[package]
edition = "2021"
name    = "day9"
version = "0.1.0"

[dependencies]
common           = { workspace = true }
itertools        = "0.10"
lending-iterator = "0.1"
nom              = { workspace = true }
